export const defaultProducts = [
  {
    id: 1,
    title: "Bananas",
    description: "Description for Bananas",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 2,
    title: "Whole Milk",
    description: "Description for Whole Milk",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 3,
    title: "Brown Bread",
    description: "Description for Brown Bread",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 4,
    title: "Eggs (12 pack)",
    description: "Description for Eggs (12 pack)",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 5,
    title: "Chicken Breast",
    description: "Description for Chicken Breast",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 6,
    title: "Apples",
    description: "Description for Apples",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 7,
    title: "Orange Juice",
    description: "Description for Orange Juice",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 8,
    title: "Cheddar Cheese",
    description: "Description for Cheddar Cheese",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 9,
    title: "Tomatoes",
    description: "Description for Tomatoes",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 10,
    title: "Potatoes",
    description: "Description for Potatoes",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 11,
    title: "Greek Yogurt",
    description: "Description for Greek Yogurt",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 12,
    title: "Spinach",
    description: "Description for Spinach",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 13,
    title: "Ground Beef",
    description: "Description for Ground Beef",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 14,
    title: "Rice",
    description: "Description for Rice",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 15,
    title: "Butter",
    description: "Description for Butter",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 16,
    title: "Carrots",
    description: "Description for Carrots",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 17,
    title: "Strawberries",
    description: "Description for Strawberries",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 18,
    title: "Pasta",
    description: "Description for Pasta",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 19,
    title: "Olive Oil",
    description: "Description for Olive Oil",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 20,
    title: "Cereal",
    description: "Description for Cereal",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
];
