export const defaultProducts = [
  {
    id: 1,
    title: "Bananas",
    brand: "Dole",
    description: "Description for Bananas",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 2,
    title: "Whole Milk",
    brand: "Horizon",
    description: "Description for Whole Milk",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 3,
    title: "Brown Bread",
    brand: "Pepperidge Farm",
    description: "Description for Brown Bread",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 4,
    title: "Eggs (12 pack)",
    brand: "Eggland's Best",
    description: "Description for Eggs (12 pack)",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 5,
    title: "Chicken Breast",
    brand: "Tyson",
    description: "Description for Chicken Breast",
    img: "https://via.placeholder.com/150",
    reviews: [
      {
        rating: 5,
        text: "Very juicy and tender, great for grilling! alhdasgdagdlaugagud ;oadgausdgao as;doaos dgsdas;od as;o das aso oa",
      },
      {
        rating: 4,
        text: "Good quality, but a bit pricey. ahdukiasd gas ;sd oasidospaid hasi9das pdfap hapdfihs aps fsa f",
      },
      {
        rating: 3,
        text: "Average taste, but easy to cook. ;asohas hsa ish f;os hifsp spi hfpishfsh fs is fshfsahfhasfh sfphsp fspf hps fps fpa fpa ",
      },
      {
        rating: 2,
        text: "Not as fresh as expected. fh;so fhsifhsapoif sif   ifshpifhsp ifsifisf",
      },
      {
        rating: 1,
        text: "Too dry and tough, wouldn't buy again.  fp'foihsafhspo ios fpsif psf psfiospofsahf pfpsoafa' pofspofpsaof oapso psfdpasohfpos pos aspo",
      },
    ],
    rating: 5,
  },
  {
    id: 6,
    title: "Apples",
    brand: "Honeycrisp",
    description: "Description for Apples",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 7,
    title: "Orange Juice",
    brand: "Tropicana",
    description: "Description for Orange Juice",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 8,
    title: "Cheddar Cheese",
    brand: "Kraft",
    description: "Description for Cheddar Cheese",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 9,
    title: "Tomatoes",
    brand: "NatureSweet",
    description: "Description for Tomatoes",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 10,
    title: "Potatoes",
    brand: "Idahoan",
    description: "Description for Potatoes",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 11,
    title: "Greek Yogurt",
    brand: "Chobani",
    description: "Description for Greek Yogurt",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 12,
    title: "Spinach",
    brand: "Earthbound Farm",
    description: "Description for Spinach",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 13,
    title: "Ground Beef",
    brand: "Certified Angus",
    description: "Description for Ground Beef",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 14,
    title: "Rice",
    brand: "Uncle Ben's",
    description: "Description for Rice",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 15,
    title: "Butter",
    brand: "Land O'Lakes",
    description: "Description for Butter",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 16,
    title: "Carrots",
    brand: "Bolthouse Farms",
    description: "Description for Carrots",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 17,
    title: "Strawberries",
    brand: "Driscoll's",
    description: "Description for Strawberries",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 18,
    title: "Pasta",
    brand: "Barilla",
    description: "Description for Pasta",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 19,
    title: "Olive Oil",
    brand: "Bertolli",
    description: "Description for Olive Oil",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 20,
    title: "Cereal",
    brand: "Kellogg's",
    description: "Description for Cereal",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
];
