export const defaultProducts = [
  {
    id: 1,
    title: "product 1",
    description: "Description for product 1",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 2,
    title: "product 2",
    description: "Description for product 2",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 3,
    title: "product 3",
    description: "Description for product 3",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 4,
    title: "product 4",
    description: "Description for product 4",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 5,
    title: "product 5",
    description: "Description for product 5",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 6,
    title: "product 6",
    description: "Description for product 6",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 7,
    title: "product 7",
    description: "Description for product 7",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 8,
    title: "product 8",
    description: "Description for product 8",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 9,
    title: "product 9",
    description: "Description for product 9",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 10,
    title: "product 10",
    description: "Description for product 10",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 11,
    title: "product 11",
    description: "Description for product 11",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 12,
    title: "product 12",
    description: "Description for product 12",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 13,
    title: "product 13",
    description: "Description for product 13",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 14,
    title: "product 14",
    description: "Description for product 14",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 15,
    title: "product 15",
    description: "Description for product 15",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
  {
    id: 16,
    title: "product 16",
    description: "Description for product 16",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 1,
  },
  {
    id: 17,
    title: "product 17",
    description: "Description for product 17",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 2,
  },
  {
    id: 18,
    title: "product 18",
    description: "Description for product 18",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 3,
  },
  {
    id: 19,
    title: "product 19",
    description: "Description for product 19",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 4,
  },
  {
    id: 20,
    title: "product 20",
    description: "Description for product 20",
    img: "https://via.placeholder.com/150",
    reviews: [],
    rating: 5,
  },
];
